//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thrifter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOwnership
    {
        public bool IsSelling { get; set; }
        public System.DateTime BuyDate { get; set; }
        public Nullable<double> OfferedPrice { get; set; }
        public string SellReason { get; set; }
        public int State { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public int ProductId { get; set; }
        public int OwnerId { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual Product Product { get; set; }
    }
}
